CREATE TABLE dp_notification (
    id BIGINT NOT NULL AUTO_INCREMENT,
    recipient_user_id BIGINT NOT NULL,
    workspace_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    notification_type VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    content VARCHAR(2000) NOT NULL,
    target_type VARCHAR(30) NOT NULL,
    target_id BIGINT NOT NULL,
    target_path VARCHAR(500) NOT NULL,
    source_type VARCHAR(30) NOT NULL,
    source_id BIGINT NOT NULL,
    dedupe_key VARCHAR(500) NOT NULL,
    status VARCHAR(10) NOT NULL DEFAULT 'UNREAD',
    read_at DATETIME(6) NULL,
    occurred_at DATETIME(6) NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_notification_recipient_dedupe (recipient_user_id, dedupe_key),
    KEY idx_notification_recipient_status_created (recipient_user_id, status, created_at, id),
    KEY idx_notification_scope_created (workspace_id, project_id, created_at, id),
    KEY idx_notification_source (source_type, source_id),
    CONSTRAINT fk_notification_recipient FOREIGN KEY (recipient_user_id) REFERENCES dp_user (id),
    CONSTRAINT fk_notification_project_scope FOREIGN KEY (project_id, workspace_id) REFERENCES dp_project (id, workspace_id),
    CONSTRAINT chk_notification_type CHECK (notification_type IN ('TASK_DUE_SOON','TASK_OVERDUE','TASK_OVERDUE_ESCALATED','TASK_REVIEW_TIMEOUT','PULL_REQUEST_REVIEW_TIMEOUT')),
    CONSTRAINT chk_notification_target CHECK (target_type IN ('TASK','PULL_REQUEST','PROJECT')),
    CONSTRAINT chk_notification_source CHECK (source_type IN ('TASK','GITHUB_PULL_REQUEST')),
    CONSTRAINT chk_notification_status CHECK (status IN ('UNREAD','READ')),
    CONSTRAINT chk_notification_read_time CHECK ((status='UNREAD' AND read_at IS NULL) OR (status='READ' AND read_at IS NOT NULL)),
    CONSTRAINT chk_notification_title CHECK (CHAR_LENGTH(title) BETWEEN 1 AND 255),
    CONSTRAINT chk_notification_content CHECK (CHAR_LENGTH(content) BETWEEN 1 AND 2000),
    CONSTRAINT chk_notification_target_path CHECK (target_path REGEXP '^/api/v1/' AND target_path NOT LIKE '%://%'),
    CONSTRAINT chk_notification_version CHECK (version >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
