CREATE TABLE dp_workspace (
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    slug VARCHAR(64) NOT NULL,
    description VARCHAR(500) NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_workspace_slug (slug),
    CONSTRAINT chk_workspace_status CHECK (status IN ('ACTIVE', 'DISABLED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE dp_project (
    id BIGINT NOT NULL AUTO_INCREMENT,
    workspace_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    project_key VARCHAR(32) NOT NULL,
    description VARCHAR(500) NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    visibility VARCHAR(20) NOT NULL DEFAULT 'PRIVATE',
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    version BIGINT NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_project_workspace_key_deleted (workspace_id, project_key, deleted),
    UNIQUE KEY uk_project_id_workspace (id, workspace_id),
    KEY idx_project_workspace_status (workspace_id, status),
    CONSTRAINT fk_project_workspace FOREIGN KEY (workspace_id) REFERENCES dp_workspace (id),
    CONSTRAINT chk_project_status CHECK (status IN ('PLANNING', 'ACTIVE', 'ARCHIVED')),
    CONSTRAINT chk_project_visibility CHECK (visibility IN ('PRIVATE', 'INTERNAL'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE dp_github_repository (
    id BIGINT NOT NULL AUTO_INCREMENT,
    workspace_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    github_repository_id BIGINT NOT NULL,
    owner_login VARCHAR(100) NOT NULL,
    repository_name VARCHAR(100) NOT NULL,
    full_name VARCHAR(201) NOT NULL,
    html_url VARCHAR(500) NULL,
    default_branch VARCHAR(255) NULL,
    visibility VARCHAR(20) NULL,
    binding_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    credential_ref VARCHAR(200) NOT NULL,
    last_synced_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    version BIGINT NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_github_repository_external_id (github_repository_id),
    UNIQUE KEY uk_github_repository_workspace_full_name_deleted (workspace_id, full_name, deleted),
    UNIQUE KEY uk_github_repository_id_scope (id, workspace_id, project_id),
    KEY idx_github_repository_project_status (workspace_id, project_id, binding_status),
    CONSTRAINT fk_github_repository_project_scope FOREIGN KEY (project_id, workspace_id)
        REFERENCES dp_project (id, workspace_id),
    CONSTRAINT chk_github_repository_binding_status CHECK (binding_status IN ('ACTIVE', 'DISABLED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE dp_github_delivery (
    id BIGINT NOT NULL AUTO_INCREMENT,
    workspace_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    repository_id BIGINT NOT NULL,
    github_delivery_id VARCHAR(100) NOT NULL,
    event_type VARCHAR(50) NOT NULL,
    action VARCHAR(50) NULL,
    signature_status VARCHAR(20) NOT NULL,
    processing_status VARCHAR(20) NOT NULL,
    payload_json JSON NOT NULL,
    payload_sha256 CHAR(64) NOT NULL,
    retry_count INT NOT NULL DEFAULT 0,
    next_retry_at DATETIME(6) NULL,
    last_error_code VARCHAR(64) NULL,
    last_error_message VARCHAR(500) NULL,
    received_at DATETIME(6) NOT NULL,
    processing_started_at DATETIME(6) NULL,
    processed_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_github_delivery_external_id (github_delivery_id),
    KEY idx_github_delivery_retry_scan (processing_status, next_retry_at),
    KEY idx_github_delivery_project_received (workspace_id, project_id, received_at DESC),
    CONSTRAINT fk_github_delivery_repository_scope FOREIGN KEY (repository_id, workspace_id, project_id)
        REFERENCES dp_github_repository (id, workspace_id, project_id),
    CONSTRAINT chk_github_delivery_signature_status CHECK (signature_status IN ('VALID', 'INVALID')),
    CONSTRAINT chk_github_delivery_processing_status CHECK (
        processing_status IN ('RECEIVED', 'PROCESSING', 'SUCCEEDED', 'FAILED', 'RETRY_WAIT', 'DEAD')
    ),
    CONSTRAINT chk_github_delivery_retry_count CHECK (retry_count >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE dp_project_activity (
    id BIGINT NOT NULL AUTO_INCREMENT,
    workspace_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    github_repository_id BIGINT NULL,
    repository_full_name VARCHAR(201) NULL,
    source_type VARCHAR(30) NOT NULL,
    activity_type VARCHAR(50) NOT NULL,
    source_delivery_id VARCHAR(100) NOT NULL,
    external_actor_id BIGINT NULL,
    actor_login VARCHAR(100) NULL,
    git_ref VARCHAR(500) NULL,
    before_sha CHAR(40) NULL,
    after_sha CHAR(40) NULL,
    commit_count INT NULL,
    head_commit_message VARCHAR(1000) NULL,
    title VARCHAR(255) NOT NULL,
    summary VARCHAR(2000) NULL,
    external_url VARCHAR(500) NULL,
    occurred_at DATETIME(6) NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_project_activity_source (source_type, source_delivery_id),
    KEY idx_project_activity_timeline (workspace_id, project_id, occurred_at DESC, id DESC),
    KEY idx_project_activity_type (workspace_id, project_id, activity_type, occurred_at DESC),
    KEY idx_project_activity_repository (github_repository_id, occurred_at DESC),
    CONSTRAINT fk_project_activity_project_scope FOREIGN KEY (project_id, workspace_id)
        REFERENCES dp_project (id, workspace_id),
    CONSTRAINT chk_project_activity_source_type CHECK (source_type IN ('GITHUB')),
    CONSTRAINT chk_project_activity_type CHECK (activity_type IN ('GITHUB_WEBHOOK_PING', 'CODE_PUSHED')),
    CONSTRAINT chk_project_activity_commit_count CHECK (commit_count IS NULL OR commit_count >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
