package com.obdeadsoup.devpilot.task.api;

import com.obdeadsoup.devpilot.framework.api.ApiResponse;
import com.obdeadsoup.devpilot.project.api.dto.PageResponse;
import com.obdeadsoup.devpilot.task.api.dto.*;
import com.obdeadsoup.devpilot.task.application.TaskApplicationService;
import com.obdeadsoup.devpilot.task.application.TaskGitHubLinkService;
import com.obdeadsoup.devpilot.task.application.TaskQueryService;
import com.obdeadsoup.devpilot.task.application.TaskWorkflowService;
import com.obdeadsoup.devpilot.task.application.command.*;
import com.obdeadsoup.devpilot.task.domain.*;
import jakarta.validation.Valid; import jakarta.validation.constraints.*;
import org.springframework.web.bind.annotation.*;
import org.springframework.validation.annotation.Validated;
import java.time.LocalDateTime; import java.util.List;

/** 已认证的 Task HTTP 入口；细粒度 Project RBAC 与 Task 属性规则全部在应用服务执行。 */
@Validated @RestController
@RequestMapping("/api/v1/workspaces/{workspaceId}/projects/{projectId}/tasks")
public class TaskController {
    private final TaskApplicationService applicationService; private final TaskWorkflowService workflowService;
    private final TaskQueryService queryService; private final TaskGitHubLinkService linkService;
    public TaskController(TaskApplicationService applicationService,TaskWorkflowService workflowService,TaskQueryService queryService,TaskGitHubLinkService linkService){this.applicationService=applicationService;this.workflowService=workflowService;this.queryService=queryService;this.linkService=linkService;}
    @PostMapping public ApiResponse<TaskResponse> create(@PathVariable @Positive long workspaceId,@PathVariable @Positive long projectId,@Valid @RequestBody CreateTaskRequest r){return ApiResponse.success(applicationService.createTask(workspaceId,projectId,new CreateTaskCommand(r.title(),r.description(),r.priority(),r.assigneeUserId(),r.dueAt())));}
    @GetMapping public ApiResponse<PageResponse<TaskResponse>> list(@PathVariable @Positive long workspaceId,@PathVariable @Positive long projectId,@RequestParam(defaultValue="1") @Min(1) int page,@RequestParam(defaultValue="20") @Min(1) @Max(100) int size,@RequestParam(required=false) TaskStatus status,@RequestParam(required=false) TaskPriority priority,@RequestParam(required=false) Long assigneeUserId,@RequestParam(required=false) Long reporterUserId,@RequestParam(required=false) LocalDateTime dueBefore){return ApiResponse.success(queryService.list(workspaceId,projectId,page,size,status,priority,assigneeUserId,reporterUserId,dueBefore));}
    @PostMapping("/from-github-issue/{issueSnapshotId}") public ApiResponse<TaskResponse> fromIssue(@PathVariable @Positive long workspaceId,@PathVariable @Positive long projectId,@PathVariable @Positive long issueSnapshotId,@Valid @RequestBody CreateTaskFromIssueRequest r){return ApiResponse.success(linkService.createTaskFromIssue(workspaceId,projectId,issueSnapshotId,new CreateTaskFromIssueCommand(r.priority(),r.assigneeUserId(),r.dueAt())));}
    @GetMapping("/{taskId}") public ApiResponse<TaskDetailResponse> get(@PathVariable @Positive long workspaceId,@PathVariable @Positive long projectId,@PathVariable @Positive long taskId){return ApiResponse.success(queryService.get(workspaceId,projectId,taskId));}
    @PutMapping("/{taskId}") public ApiResponse<TaskResponse> update(@PathVariable @Positive long workspaceId,@PathVariable @Positive long projectId,@PathVariable @Positive long taskId,@Valid @RequestBody UpdateTaskRequest r){return ApiResponse.success(applicationService.updateTaskProfile(workspaceId,projectId,taskId,new UpdateTaskCommand(r.title(),r.description(),r.priority(),r.dueAt(),r.expectedVersion())));}
    @PostMapping("/{taskId}/assign") public ApiResponse<TaskResponse> assign(@PathVariable @Positive long workspaceId,@PathVariable @Positive long projectId,@PathVariable @Positive long taskId,@Valid @RequestBody AssignTaskRequest r){return ApiResponse.success(applicationService.assignTask(workspaceId,projectId,taskId,r.assigneeUserId(),r.expectedVersion()));}
    @PostMapping("/{taskId}/unassign") public ApiResponse<TaskResponse> unassign(@PathVariable @Positive long workspaceId,@PathVariable @Positive long projectId,@PathVariable @Positive long taskId,@Valid @RequestBody TaskActionRequest r){return ApiResponse.success(applicationService.unassignTask(workspaceId,projectId,taskId,r.expectedVersion()));}
    @PostMapping("/{taskId}/plan") public ApiResponse<TaskResponse> plan(@PathVariable long workspaceId,@PathVariable long projectId,@PathVariable long taskId,@Valid @RequestBody TaskActionRequest r){return action(workspaceId,projectId,taskId,r,TaskAction.PLANNED);}
    @PostMapping("/{taskId}/return-to-backlog") public ApiResponse<TaskResponse> back(@PathVariable long workspaceId,@PathVariable long projectId,@PathVariable long taskId,@Valid @RequestBody TaskActionRequest r){return action(workspaceId,projectId,taskId,r,TaskAction.RETURNED_TO_BACKLOG);}
    @PostMapping("/{taskId}/start") public ApiResponse<TaskResponse> start(@PathVariable long workspaceId,@PathVariable long projectId,@PathVariable long taskId,@Valid @RequestBody TaskActionRequest r){return action(workspaceId,projectId,taskId,r,TaskAction.STARTED);}
    @PostMapping("/{taskId}/submit-for-review") public ApiResponse<TaskResponse> submit(@PathVariable long workspaceId,@PathVariable long projectId,@PathVariable long taskId,@Valid @RequestBody TaskActionRequest r){return action(workspaceId,projectId,taskId,r,TaskAction.SUBMITTED_FOR_REVIEW);}
    @PostMapping("/{taskId}/request-changes") public ApiResponse<TaskResponse> changes(@PathVariable long workspaceId,@PathVariable long projectId,@PathVariable long taskId,@Valid @RequestBody TaskActionRequest r){return action(workspaceId,projectId,taskId,r,TaskAction.CHANGES_REQUESTED);}
    @PostMapping("/{taskId}/complete") public ApiResponse<TaskResponse> complete(@PathVariable long workspaceId,@PathVariable long projectId,@PathVariable long taskId,@Valid @RequestBody TaskActionRequest r){return action(workspaceId,projectId,taskId,r,TaskAction.COMPLETED);}
    @PostMapping("/{taskId}/cancel") public ApiResponse<TaskResponse> cancel(@PathVariable long workspaceId,@PathVariable long projectId,@PathVariable long taskId,@Valid @RequestBody TaskActionRequest r){return action(workspaceId,projectId,taskId,r,TaskAction.CANCELED);}
    @PostMapping("/{taskId}/reopen") public ApiResponse<TaskResponse> reopen(@PathVariable long workspaceId,@PathVariable long projectId,@PathVariable long taskId,@Valid @RequestBody TaskActionRequest r){return action(workspaceId,projectId,taskId,r,TaskAction.REOPENED);}
    @PostMapping("/{taskId}/github-links") public ApiResponse<TaskResponse> link(@PathVariable @Positive long workspaceId,@PathVariable @Positive long projectId,@PathVariable @Positive long taskId,@Valid @RequestBody CreateTaskGitHubLinkRequest r){return ApiResponse.success(r.resourceType()==TaskGitHubResourceType.ISSUE?linkService.linkIssue(workspaceId,projectId,taskId,r.snapshotId(),r.expectedTaskVersion(),r.relationType()):linkService.linkPullRequest(workspaceId,projectId,taskId,r.snapshotId(),r.expectedTaskVersion(),r.relationType()));}
    @GetMapping("/{taskId}/github-links") public ApiResponse<List<TaskGitHubLinkResponse>> links(@PathVariable @Positive long workspaceId,@PathVariable @Positive long projectId,@PathVariable @Positive long taskId){return ApiResponse.success(linkService.listGitHubLinks(workspaceId,projectId,taskId));}
    @PostMapping("/{taskId}/github-links/{linkId}/remove") public ApiResponse<TaskResponse> remove(@PathVariable @Positive long workspaceId,@PathVariable @Positive long projectId,@PathVariable @Positive long taskId,@PathVariable @Positive long linkId,@Valid @RequestBody RemoveTaskGitHubLinkRequest r){return ApiResponse.success(linkService.removeGitHubLink(workspaceId,projectId,taskId,linkId,r.expectedTaskVersion(),r.expectedLinkVersion()));}
    private ApiResponse<TaskResponse> action(long w,long p,long id,TaskActionRequest r,TaskAction a){return ApiResponse.success(switch(a){case PLANNED->workflowService.planTask(w,p,id,r.expectedVersion(),r.reason());case RETURNED_TO_BACKLOG->workflowService.returnToBacklog(w,p,id,r.expectedVersion(),r.reason());case STARTED->workflowService.startTask(w,p,id,r.expectedVersion(),r.reason());case SUBMITTED_FOR_REVIEW->workflowService.submitForReview(w,p,id,r.expectedVersion(),r.reason());case CHANGES_REQUESTED->workflowService.requestChanges(w,p,id,r.expectedVersion(),r.reason());case COMPLETED->workflowService.completeTask(w,p,id,r.expectedVersion(),r.reason());case CANCELED->workflowService.cancelTask(w,p,id,r.expectedVersion(),r.reason());case REOPENED->workflowService.reopenTask(w,p,id,r.expectedVersion(),r.reason());case CREATED->throw new IllegalArgumentException();});}
}
