package com.obdeadsoup.devpilot.notification.domain;
public enum NotificationType {
    TASK_DUE_SOON,
    TASK_OVERDUE,
    TASK_OVERDUE_ESCALATED,
    TASK_REVIEW_TIMEOUT,
    PULL_REQUEST_REVIEW_TIMEOUT,
    TASK_ASSIGNED,
    TASK_UNASSIGNED,
    TASK_SUBMITTED_FOR_REVIEW,
    TASK_CHANGES_REQUESTED,
    TASK_COMPLETED,
    TASK_REOPENED
}
