package com.obdeadsoup.devpilot.audit.domain;

public enum AuditActionType {
    OUTBOX_REPLAY_REQUESTED,
    OUTBOX_REPLAY_CREATED,
    OUTBOX_REPLAY_REJECTED,
    GITHUB_SYNC_REPLAY_REQUESTED,
    GITHUB_SYNC_REPLAY_CREATED,
    GITHUB_SYNC_REPLAY_REJECTED,
    OUTBOX_DEAD_VIEWED,
    GITHUB_SYNC_DEAD_VIEWED
}
