package com.obdeadsoup.devpilot.project.domain;

public enum WorkspacePermission {

    WORKSPACE_READ,
    WORKSPACE_UPDATE,
    WORKSPACE_DELETE,
    WORKSPACE_TRANSFER_OWNERSHIP,
    WORKSPACE_MEMBER_LIST,
    WORKSPACE_MEMBER_INVITE,
    WORKSPACE_MEMBER_ROLE_UPDATE,
    WORKSPACE_MEMBER_REMOVE,
    PROJECT_CREATE,
    WORKSPACE_AUDIT_READ,
    WORKSPACE_AGENT_POLICY_MANAGE
}
